
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - frontend/.env
    command: npm run dev

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - backend/cmd/server/.env